### ISSUE TITLE
Typora app 的bug

### ISSUE THREAD

**Issue by yezisui** [TrialMacApp/TrialMacApp#1]
**你的macOS版本和芯片版本**
-Apple M1，15.0.1 (24A348)

**哪个软件和软件版本是什么**
-Typora 1.9.4

**有什么错误信息**
-终端提示注入失败，签名完成。软件内并没有激活成功。请告知解决方法，谢谢您

**Comment by TrialMacApp** [comment]
可以使用最新版本的GUI操作，我这里测试可以。

**Comment by yezisui** [comment]
> 可以使用最新版本的GUI操作，我这里测试可以。

好的 感谢🙏
