### ISSUE TITLE
闪卡 MAS 的支持请求

### ISSUE THREAD

**Issue by heiwhatsup** [TrialMacApp/TrialMacApp#2]
**是否官方提供了试用版本（如果没有就不要提了）**
-是

**哪个软件和官方下载链接**
-[闪卡](https://apps.apple.com/us/app/%E9%97%AA%E5%8D%A1-%E5%A4%8D%E4%B9%A0%E5%A4%87%E8%80%83-%E5%AD%A6%E9%9C%B8%E7%AC%94%E8%AE%B0/id1515687192?l=zh-Hans-CN)

**有没有免费可替代品**
-有,但不好用

**Comment by inject-X** [comment]
https://github.com/inject-X/injectX support it.
