### ISSUE TITLE
xxx app 的bug

### ISSUE THREAD

**Issue by kai2ou** [TrialMacApp/TrialMacApp#3]
**你的macOS版本和芯片版本**
- Mac mini 4 m4，15.1

**哪个软件和软件版本是什么**
-

**有什么错误信息**
-
点试用，没有任何反应。

**Comment by TrialMacApp** [comment]
哪个软件和软件版本是什么 每个信息都写全啊

**Comment by kai2ou** [comment]
> 哪个软件和软件版本是什么 每个信息都写全啊

测试了几个软件都不行，包括cleanmymac、Permute 3、infuse，都是点了试用没有任何反应

**Comment by TrialMacApp** [comment]
设置 - 隐私 - app管理 这里把TrialMacAppGUI打开

**Comment by kai2ou** [comment]
打开了，还是一样没任何反应

**Comment by TrialMacApp** [comment]
录一个视频看看
