### ISSUE TITLE
xxx app 的bug

### ISSUE THREAD

**Issue by wetzel** [TrialMacApp/TrialMacApp#4]
**你的macOS版本和芯片版本**
- macOS macOS 15.2 (24C101), M4 Pro

**哪个软件和软件版本是什么**
- Ulysses 36.2 (78363)

**有什么错误信息**
- Can't be patched
![CleanShot 2024-12-24 at 16 57 53@2x](https://github.com/user-attachments/assets/f3ac6392-d78f-4f59-8d28-4f69e6d0076a)

**Comment by kai2ou** [comment]
同样的问题，偶尔行、偶尔不行，需要多次重启

**Comment by TrialMacApp** [comment]
> 同样的问题，偶尔行、偶尔不行，需要多次重启

https://github.com/TrialMacApp/TrialMacApp/releases/tag/1.2-25

**Comment by kai2ou** [comment]
1.2-25版本完美了

**Comment by TrialMacApp** [comment]
https://github.com/TrialMacApp/TrialMacApp/releases/tag/1.2-25
